name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
        contents: write
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Setup Node.js
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '16' 

    - name: Install and Build 🔧
      run: |
        yarn install
        yarn build
    - name: Setup Pages
      uses: actions/configure-pages@v3
      with:
        enablement: true
        token: ${{ secrets.PAGES_TOKEN }}
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        # Upload entire repository
        path: 'build'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
